//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pspasp.Models.Enty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Soru
    {
        public short Soruİd { get; set; }
        public string Sorular { get; set; }
    }
}
